export const REWRITE_ITEMS = 'REWRITE_ITEMS';
export const ADD_ITEMS = 'ADD_ITEMS';
export const REWRITE_NEXT_PAGE_TOKEN = 'REWRITE_NEXT_PAGE_TOKEN';
export const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING';
export const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK';
export const DELETE_FROM_BOOKMARK = 'DELETE+FROM_BOOKMARK';
